name: Deploy Pipeline

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  deploy_dev:
    uses: ./.github/workflows/deploy-dev.yml
    needs: []

  deploy_qa:
    needs: deploy_dev
    uses: ./.github/workflows/deploy-qa.yml

  deploy_uat:
    needs: deploy_qa
    uses: ./.github/workflows/deploy-uat.yml

  deploy_prod:
    needs: deploy_uat
    uses: ./.github/workflows/deploy-prod.yml
