name: Deploy Pipeline

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  extract_repo_name:
    runs-on: ubuntu-latest
    outputs:
      repo_name: ${{ steps.extract_repo_name.outputs.repo_name }}
    steps:
      - name: Extract Repository Name
        id: extract_repo_name
        run: echo "::set-output name=repo_name::${GITHUB_REPOSITORY##*/}"

  deploy_dev:
    needs: extract_repo_name
    uses: ./.github/workflows/deploy-dev.yml
    with:
      repo_name: ${{ needs.extract_repo_name.outputs.repo_name }}

  deploy_qa:
    needs: deploy_dev
    uses: ./.github/workflows/deploy-qa.yml
    with:
      repo_name: ${{ needs.extract_repo_name.outputs.repo_name }}

  deploy_uat:
    needs: deploy_qa
    uses: ./.github/workflows/deploy-uat.yml
    with:
      repo_name: ${{ needs.extract_repo_name.outputs.repo_name }}

  deploy_prod:
    needs: deploy_uat
    uses: ./.github/workflows/deploy-prod.yml
    with:
      repo_name: ${{ needs.extract_repo_name.outputs.repo_name }}
